const API_BASE="";
const PROJECT_STATUS={activeModel:"v2",candidateModel:"v1",drift:"Normal",f1:.6403,auc:.8777,accuracy:.8190,precision:.6776,recall:.6070,retraining:"Rejected",trigger:"Candidate failed evaluation",decision:"Rejected"};
const titles={dashboard:["Production Overview","Monitor your ML model in production."],prediction:["Make Prediction","Send customer data to the active production model."],monitoring:["Model Monitoring","Track drift, performance and system reliability."],models:["Models & Retraining","Inspect model versions and retraining decisions."],alerts:["System Alerts","Review important production ML events."]};
document.querySelectorAll(".nav-item").forEach(btn=>btn.addEventListener("click",()=>{const page=btn.dataset.page;document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.remove("active-page"));document.getElementById(page).classList.add("active-page");document.getElementById("pageTitle").textContent=titles[page][0];document.getElementById("pageSubtitle").textContent=titles[page][1]}));
function risk(p){if(p>=.7)return["High","risk-high"];if(p>=.3)return["Medium","risk-medium"];return["Low","risk-low"]}
function applyProjectMetrics(){document.getElementById("activeModel").textContent=PROJECT_STATUS.activeModel;document.getElementById("currentModel").textContent=PROJECT_STATUS.activeModel;document.getElementById("candidateModel").textContent=PROJECT_STATUS.candidateModel;document.getElementById("driftStatus").textContent=PROJECT_STATUS.drift;document.getElementById("modelF1").textContent=PROJECT_STATUS.f1.toFixed(4);document.getElementById("modelAuc").textContent=PROJECT_STATUS.auc.toFixed(4);document.getElementById("retrainStatus").textContent=PROJECT_STATUS.retraining;document.getElementById("retrainTrigger").textContent=PROJECT_STATUS.trigger;document.getElementById("retrainDecision").textContent=PROJECT_STATUS.decision}
function renderLogs(logs){if(!Array.isArray(logs))logs=[];const clean=logs.map(x=>({timestamp:x.timestamp||x.time||"",prediction:Number(x.prediction??0),probability:Number(x.prediction_probability??x.churn_probability??x.probability??0),model:x.model_version||"—"})).filter(x=>Number.isFinite(x.probability));document.getElementById("totalPredictions").textContent=clean.length;document.getElementById("highRisk").textContent=clean.filter(x=>x.probability>=.7).length;const avg=clean.length?clean.reduce((a,b)=>a+b.probability,0)/clean.length:0;document.getElementById("avgRisk").textContent=(avg*100).toFixed(1)+"%";document.getElementById("predictionTable").innerHTML=clean.slice(-12).reverse().map(x=>{const[r,c]=risk(x.probability);return`<tr><td>${escapeHtml(x.timestamp)}</td><td>${x.prediction}</td><td>${(x.probability*100).toFixed(1)}%</td><td>${escapeHtml(x.model)}</td><td class="${c}">${r}</td></tr>`}).join("")||`<tr><td colspan="5">No prediction logs yet.</td></tr>`;renderChart("predictionChart",[["No Churn",clean.filter(x=>x.prediction===0).length],["Churn",clean.filter(x=>x.prediction===1).length]]);renderChart("riskChart",[["Low",clean.filter(x=>x.probability<.3).length],["Medium",clean.filter(x=>x.probability>=.3&&x.probability<.7).length],["High",clean.filter(x=>x.probability>=.7).length]])}
function renderChart(id,items){const el=document.getElementById(id),max=Math.max(...items.map(x=>x[1]),1);el.innerHTML=items.map(x=>`<div class="bar"><em>${x[1]}</em><i style="height:${Math.max(10,(x[1]/max)*130)}px"></i><span>${x[0]}</span></div>`).join("")}
function renderModels(active){const versions=[{version:"v2",active:active==="v2",description:"Production model. Current active model after evaluation."},{version:"v1",active:active==="v1",description:"Previous/candidate model. Rejected because it did not outperform v2."}];document.getElementById("modelList").innerHTML=versions.map(m=>`<div class="model-card ${m.active?"active":"archived"}"><span class="tag">${m.active?"PRODUCTION":"ARCHIVED"}</span><h3>Model ${m.version}</h3><p>${escapeHtml(m.description)}</p></div>`).join("")}
async function getJSON(path){const r=await fetch(API_BASE+path);if(!r.ok)throw new Error("HTTP "+r.status);return r.json()}
async function loadLogs(){try{renderLogs(await getJSON("/logs"))}catch(e){renderLogs([])}}
async function refresh(){applyProjectMetrics();try{await getJSON("/api/health");document.getElementById("apiStatus").textContent="Connected"}catch(e){document.getElementById("apiStatus").textContent="Offline"}try{const m=await getJSON("/model"),a=m.active_model||PROJECT_STATUS.activeModel;renderModels(a);document.getElementById("activeModel").textContent=a;document.getElementById("currentModel").textContent=a}catch(e){renderModels(PROJECT_STATUS.activeModel)}await loadLogs()}
document.getElementById("refreshBtn").addEventListener("click",refresh);
document.getElementById("predictionForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.target);const payload={Gender:Number(f.get("Gender")),Senior_Citizen:Number(f.get("Senior_Citizen")),Partner:Number(f.get("Partner")),Dependents:Number(f.get("Dependents")),Tenure_Months:Number(f.get("Tenure_Months")),Phone_Service:Number(f.get("Phone_Service")),Multiple_Lines:f.get("Multiple_Lines"),Internet_Service:f.get("Internet_Service"),Online_Security:f.get("Online_Security"),Online_Backup:f.get("Online_Backup"),Device_Protection:f.get("Device_Protection"),Tech_Support:f.get("Tech_Support"),Streaming_TV:f.get("Streaming_TV"),Streaming_Movies:f.get("Streaming_Movies"),Contract:f.get("Contract"),Paperless_Billing:Number(f.get("Paperless_Billing")),Payment_Method:f.get("Payment_Method"),Monthly_Charges:Number(f.get("Monthly_Charges")),Total_Charges:Number(f.get("Total_Charges"))};try{const r=await fetch(`${API_BASE}/predict`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),data=await r.json();if(!r.ok)throw new Error(`HTTP ${r.status} - ${JSON.stringify(data)}`);const p=Number(data.churn_probability??data.prediction_probability??data.probability??0),pred=Number(data.prediction),[level]=risk(p),el=document.getElementById("predictionResult");el.classList.remove("hidden");document.getElementById("resultTitle").textContent=`${level} Risk`;document.getElementById("resultProbability").textContent=`${(p*100).toFixed(1)}%`;document.getElementById("resultText").textContent=pred===1?"The model predicts that this customer is likely to churn.":"The model predicts that this customer is likely to stay.";document.getElementById("resultIcon").textContent=pred===1?"!":"✓";el.scrollIntoView({behavior:"smooth",block:"center"});await refresh()}catch(err){console.error(err);alert(`Prediction failed.\n\n${err.message}`)}});
function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;",'\'':"&#039;"}[m]))}
applyProjectMetrics();renderModels(PROJECT_STATUS.activeModel);renderLogs([]);refresh();
